apiVersion: v1
kind: Pod
metadata:
  name: flask-app
spec:
  containers:
    - name: flask-app
      image: nehapardeshi03/flask-mongodb-app:latest
      ports:
        - containerPort: 5000
      env:
        - name: FLASK_ENV
          value: "development"
      volumeMounts:
        - name: config-volume
          mountPath: /app/config
  volumes:
    - name: config-volume
      configMap:
        name: app-config

